version: '3.8'
services:
  perfectpick_announcements_db:
    build: ./PerfectPick_Announcements_db
    container_name: perfectpick_announcements_db
    ports:
      - "3306:3306" 
    volumes:
      - "./PerfectPick_Announcements_db/data:/var/lib/mysql" 
    tty: true
    stdin_open: true

networks:
  perfectpicknetwork:
    external: true
